default:
  image: python:3.9

stages:
  - build
  - test
  - badges

# run-unit-tests:
#   stage: test
#   script:
#     - python -m pip install --upgrade pip # why isn't environment persisting between stages?
#     - pip install -r requirements.txt
#     - coverage run -m pytest

create-badges:
  stage: badges
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - coverage run -m pytest
    - coverage report
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"


